"""testing

Revision ID: 487069c32352
Revises: 13e08f738c91
Create Date: 2025-03-13 07:20:33.751773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487069c32352'
down_revision: Union[str, None] = '13e08f738c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    if conn.dialect.has_index(conn, 'address', 'ix_address_id'):
        op.drop_index('ix_address_id', table_name='address')
    op.drop_table('address')
    op.drop_constraint('todos_address_id_fkey', 'todos', type_='foreignkey')
    op.drop_column('todos', 'address_id')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('todos', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('todos_address_id_fkey', 'todos', 'address', ['address_id'], ['id'], ondelete='CASCADE')
    op.create_table('address',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('zipcode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='address_pkey')
    )
    op.create_index('ix_address_id', 'address', ['id'], unique=False)
    # ### end Alembic commands ###
